
modLoader="javafml" #mandatory

loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="cagerium" #mandatory

version="${file.jarVersion}" #mandatory

displayName="cagerium" #mandatory

authors="MehVahdJukaar" #optional

description='''Compact Mob Farms'''


[[dependencies.cagerium]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.0.36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.cagerium]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19]"
    ordering="NONE"
    side="BOTH"
